dataset: image_folder
num_classes: 1000
train_split: train
val_split: validation
batch_size: 1024
img_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
# aa: rand-m9-mstd0.5-inc1
# mixup: 0.8
# mixup_off_epoch: 175
# mixup_prob: 1.0
# mixup_mode: batch
# mixup_switch_prob: 0.5
# cutmix: 1.0
# reprob: 0.25
remode: pixel
scale:
    - 0
    - 1.0
lr: 1e-2
min_lr: 1e-5
warmup_epochs: 0
sched: cosine
opt: sgd
smoothing: 0.1
weight-decay: 2e-3
epochs: 100
workers: 4
world_size: 1
multiprocessing_distributed: True

checkpoint_hist: 1
sync_bn: True
pin_mem: True

use_kd: False
teacher: ResNet18
teacher_checkpoint: output/train/20250427-184912-ResNet18-224/best.pth.tar.pth
initial_checkpoint: output/train/20250605-173623-ResNet18-224/best.pth.tar.pth
# resume: output/train/20250423-124710-ResNet18-224/last.pth.tar
powerof2: True
log_name: resnet18_imagenet_avgpool_acc15_0606
wq_per_channel: True
wq_enable: True
wq_asym: True
wq_mode: "LSQ"
wq_bitw: 32
aq_enable: True
aq_asym: True
aq_mode: "LSQ"
aq_bitw: 32
resq_enable: True
resq_mode: "LSQ"
resq_bitw: 16
reg_weight: 0
# w4a4
bw_list: 4, 4, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 2
ba_list: 6, 6, 6, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4
# original
# bw_list: 5, 5, 5, 5, 5, 4, 4, 3, 4, 3, 3, 3, 3, 2, 2, 2
# ba_list: 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3
qmodules: 
  - "convbn_first;wq:bit:8;aq:bit:8"
  - "layer1.0.convbn1"
  - "layer1.0.convbn2"
  - "layer1.1.convbn1"
  - "layer1.1.convbn2"
  - "layer2.0.convbn1"
  - "layer2.0.convbn2"
  # - "layer2.0.shortcut.0"
  - "layer2.1.convbn1"
  - "layer2.1.convbn2"
  - "layer3.0.convbn1"
  - "layer3.0.convbn2"
  # - "layer3.0.shortcut.0"
  - "layer3.1.convbn1"
  - "layer3.1.convbn2"
  - "layer4.0.convbn1"
  - "layer4.0.convbn2"
  # - "layer4.0.shortcut.0"
  - "layer4.1.convbn1"
  - "layer4.1.convbn2"
  - fc;wq:bit:8;aq:bit:8
resq_modules:
    - relu
    - layer1.0.relu2
    - layer1.1.relu2
    - layer2.0.relu2
    - layer3.0.downsample
    - layer2.1.relu2
    - layer3.0.relu2
    - layer3.0.downsample
    - layer3.1.relu2
    - layer4.0.downsample
    - layer4.0.relu2
    - layer4.1.relu2
