dataset: imagenet
num_classes: 1000
train_split: train
val_split: validation
batch_size: 512
img_size: 256
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
mixup_prob: 0.0
mixup_mode: batch
mixup_switch_prob: 0.0
cutmix: 0
reprob: 0
remode: pixel
scale:
    - 0
    - 1.0
lr: 0.01
min_lr: 1e-4
sched: cosine
opt: sgd
smoothing: 0.1
weight-decay: 1e-4
epochs: 60
workers: 4
world_size: 1
multiprocessing_distributed: True
dist_url: 'tcp://127.0.0.1:8087'
dist_backend: "nccl"
rank: 0
log_name: image_test3
checkpoint_hist: 1
sync_bn: True
pin_mem: True
no_prefetcher: False

use_kd: True
teacher: ResNet18
teacher_checkpoint: pretrained/resnet18_image.pth
initial_checkpoint: pretrained/resnet18_image.pth
powerof2: True

wq_per_channel: True
wq_enable: True
wq_mode: "LSQ"
wq_bitw: 4
aq_enable: True
aq_asym: True
aq_mode: "LSQ"
aq_bitw: 4
resq_enable: True
resq_mode: "LSQ"
resq_bitw: 16
qmodules: 
#   - "convbn_first;wq:bit:8;aq:bit:8"
  - "layer1.0.convbn1"
  - "layer1.0.convbn2"
  - "layer1.1.convbn1"
  - "layer1.1.convbn2"
  - "layer2.0.convbn1"
  - "layer2.0.convbn2"
  # - "layer2.0.shortcut.0"
  - "layer2.1.convbn1"
  - "layer2.1.convbn2"
  - "layer3.0.convbn1"
  - "layer3.0.convbn2"
  # - "layer3.0.shortcut.0"
  - "layer3.1.convbn1"
  - "layer3.1.convbn2"
  - "layer4.0.convbn1"
  - "layer4.0.convbn2"
  # - "layer4.0.shortcut.0"
  - "layer4.1.convbn1"
  - "layer4.1.convbn2"
#   - fc;wq:bit:8;aq:bit:8
resq_modules:
    - relu
    - layer1.0.relu2
    - layer1.1.relu2
    - layer2.0.relu2
    - layer3.0.downsample
    - layer2.1.relu2
    - layer3.0.relu2
    - layer3.0.downsample
    - layer3.1.relu2
    - layer4.0.downsample
    - layer4.0.relu2
    - layer4.1.relu2
