dataset: image_folder
num_classes: 1000
train_split: train
val_split: validation
batch_size: 1024
img_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
mixup_prob: 0.0
mixup_mode: batch
mixup_switch_prob: 0.0
cutmix: 0
reprob: 0
remode: pixel
scale:
    - 0
    - 1.0
lr: 0.01
min_lr: 1e-4
warmup_epochs: 10
sched: cosine
opt: sgd
smoothing: 0.1
weight-decay: 1e-4
epochs: 200
workers: 4
world_size: 1
multiprocessing_distributed: True


checkpoint_hist: 1
sync_bn: True
pin_mem: True

use_kd: False
teacher: ResNet18
teacher_checkpoint: pretrained/resnet18_image.pth
initial_checkpoint: pretrained/resnet18_image.pth
# resume: output/train/20250423-124710-ResNet18-224/last.pth.tar
powerof2: True
log_name: resnet18_imagenet_avgpool
wq_per_channel: True
wq_enable: False
wq_mode: "LSQ"
wq_bitw: 32
aq_enable: False
aq_asym: True
aq_mode: "LSQ"
aq_bitw: 32
resq_enable: False
resq_mode: "LSQ"
resq_bitw: 16
# w4a4
# bw_list: 4, 4, 4, 4, 4, 3, 4, 3, 3, 4, 3, 3, 3, 3, 2, 3
# ba_list: 4, 4, 4, 4, 4, 4, 3, 4, 4, 2, 3, 3, 3, 2, 3, 2
qmodules: 
  - "convbn_first;wq:bit:8;aq:bit:8"
  - "layer1.0.convbn1"
  - "layer1.0.convbn2"
  - "layer1.1.convbn1"
  - "layer1.1.convbn2"
  - "layer2.0.convbn1"
  - "layer2.0.convbn2"
  # - "layer2.0.shortcut.0"
  - "layer2.1.convbn1"
  - "layer2.1.convbn2"
  - "layer3.0.convbn1"
  - "layer3.0.convbn2"
  # - "layer3.0.shortcut.0"
  - "layer3.1.convbn1"
  - "layer3.1.convbn2"
  - "layer4.0.convbn1"
  - "layer4.0.convbn2"
  # - "layer4.0.shortcut.0"
  - "layer4.1.convbn1"
  - "layer4.1.convbn2"
  - fc;wq:bit:8;aq:bit:8
resq_modules:
    - relu
    - layer1.0.relu2
    - layer1.1.relu2
    - layer2.0.relu2
    - layer3.0.downsample
    - layer2.1.relu2
    - layer3.0.relu2
    - layer3.0.downsample
    - layer3.1.relu2
    - layer4.0.downsample
    - layer4.0.relu2
    - layer4.1.relu2
